[project]
authors = ["aegroto <aegroto@protonmail.com>"]
channels = ["conda-forge"]
description = "Community Guard Telegram Bot"
name = "community-guard-bot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
"run" = "python -m main"

[dependencies]
python = ">=3.13.0,<4"
