[project]
authors = ["aegroto <aegroto@protonmail.com>"]
channels = ["conda-forge"]
description = "Community Guard Telegram Bot"
name = "community-guard-bot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
"run" = "python -m main"

format = "ruff format"
lint = "ruff check"

[dependencies]
python = ">=3.13.0,<4"
ruff = ">=0.6.8,<0.7"

[pypi-dependencies]
aiohttp = ">=3.11.7, <4"
