name: Docker Image CI

on:
  push:
    branches: [ "main", "features/versioning" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: community-guard-bot
  PROJECT: gdgcatania

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog
          @codedependant/semantic-release-docker

#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#  build-and-publish:
#    # run the job on the latest ubuntu
#    runs-on: ubuntu-latest
#    # add permissions to github token
#    permissions:
#      contents: read
#      packages: write
#      attestations: write
#      id-token: write
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Log in to the Container registry with Github Token
#        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#
#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
